// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwXsx-0nskNw7nBqtnK5qSQkOyWwa-JtQ',
    appId: '1:517272680107:web:68fc82df410f7a99d229ee',
    messagingSenderId: '517272680107',
    projectId: 'voter-867fd',
    authDomain: 'voter-867fd.firebaseapp.com',
    storageBucket: 'voter-867fd.firebasestorage.app',
    measurementId: 'G-R9VVQDXTSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8G1ctTRZQm3rGYrkRhzCp_hZ55stAo18',
    appId: '1:517272680107:android:4d41b84d397572a2d229ee',
    messagingSenderId: '517272680107',
    projectId: 'voter-867fd',
    storageBucket: 'voter-867fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ5rqsY2vHLeX7kewIshOleEl9ufDNJZ8',
    appId: '1:517272680107:ios:6ae15f3d0abdc920d229ee',
    messagingSenderId: '517272680107',
    projectId: 'voter-867fd',
    storageBucket: 'voter-867fd.firebasestorage.app',
    iosBundleId: 'com.example.voter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ5rqsY2vHLeX7kewIshOleEl9ufDNJZ8',
    appId: '1:517272680107:ios:6ae15f3d0abdc920d229ee',
    messagingSenderId: '517272680107',
    projectId: 'voter-867fd',
    storageBucket: 'voter-867fd.firebasestorage.app',
    iosBundleId: 'com.example.voter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwXsx-0nskNw7nBqtnK5qSQkOyWwa-JtQ',
    appId: '1:517272680107:web:72e52b9d7d10d0ced229ee',
    messagingSenderId: '517272680107',
    projectId: 'voter-867fd',
    authDomain: 'voter-867fd.firebaseapp.com',
    storageBucket: 'voter-867fd.firebasestorage.app',
    measurementId: 'G-2920CBCZD9',
  );

}